### ISSUE TITLE
file upload issue

### ISSUE THREAD

**Issue by orionla2** [dmitrovskiy/docker-nginx-php-fpm#1]
Hello

It is an issue when creating upload request.

Default file uploader from Silex;

Request via Postman
Body: form-data
Method: POST

About file:
FileName: img.jpg
FileSize: 7kb

As you can see it's not an issue related with type of file. 
Without any changes upload request gave error:500 and description:
"file could not be uploaded: missing temporary directory"

So I checked:

`echo sys_get_temp_dir(); // return /tmp`
`ini_get('upload_temp_dir'); // return  nothing`
`phpinfo() // return upload_temp_dir: undefined`

After that I took php.ini from /etc/php5/php.ini (this path from phpinfo) and copied it localy. Modified string
`upload_temp_dir=` to `upload_temp_dir=/tmp`

At the dockerfile I made 

`RUN rm /etc/php5/php.ini`
`COPY ./src/php.ini /etc/php5/php.ini
`

Error about missing temp folder gone, but still no files in /tmp folder on upload and as a result error on transfer from temp folder to destination folder.

**Comment by dmitrovskiy** [comment]
Hello. Thank you for the issue and thank you @wildsurfer for the fix! 
https://github.com/dmitrovskiy/docker-nginx-php-fpm/commit/8421874de362c03c15a87344c4269293046c771c
